### ISSUE TITLE
Local on Sign in can't cancel

### ISSUE THREAD

**Issue by miljkovicjovan** [igorashs/library#3]
In local mode when you click on Sign in you can't cancel out and return back.
I would like to contribute and fix if you like

**Comment by igorashs** [comment]
@miljkovicjovan Heyo, U are welcome to :shipit:

**Comment by miljkovicjovan** [comment]
I have looked through the code and can't seem to figure out how your pop up works so I am gonna leave it sorry

**Comment by igorashs** [comment]
No worries :shipit:
